mex -v ...
    -I../algebra3d/include/algebra3d/  ...
    -I../cgDNAprecon/include/cgDNAprecon/ ...
    -lm -lblas -llapack -lpthread  ...
    -L../algebra3d/lib/ -lalgebra3d  ...
    -L../cgDNAprecon/lib/ -lcgDNAprecon  ...
    cgDNApmc.cpp randgen.cpp helpers.cpp cgDNAutils.cpp

